const mockedEmptyCart = {
  data: {
    id: 76151,
    number: 'R537677469',
    itemTotal: '0.0',
    total: '0.0',
    shipTotal: '0.0',
    state: 'cart',
    adjustmentTotal: '0.0',
    userId: 2320,
    createdAt: '2020-06-03T16:22:15.034Z',
    updatedAt: '2020-06-03T16:22:15.034Z',
    completedAt: null,
    paymentTotal: '0.0',
    shipmentState: null,
    paymentState: null,
    email: 'francois@chord.co',
    specialInstructions: null,
    channel: 'spree',
    includedTaxTotal: '0.0',
    additionalTaxTotal: '0.0',
    displayIncludedTaxTotal: '$0.00',
    displayAdditionalTaxTotal: '$0.00',
    taxTotal: '0.0',
    currency: 'USD',
    coveredByStoreCredit: true,
    displayTotalApplicableStoreCredit: '$0.00',
    orderTotalAfterStoreCredit: '0.0',
    displayOrderTotalAfterStoreCredit: '$0.00',
    totalApplicableStoreCredit: '0.0',
    displayTotalAvailableStoreCredit: '$0.00',
    displayStoreCreditRemainingAfterCapture: '$0.00',
    cancelerId: null,
    displayItemTotal: '$0.00',
    totalQuantity: 0,
    displayTotal: '$0.00',
    displayShipTotal: '$0.00',
    displayTaxTotal: '$0.00',
    token: 'BvauHNJwLY8iqUu0UO0MNA',
    checkoutSteps: ['address', 'delivery', 'confirm', 'complete'],
    paymentMethods: [
      { id: 23, name: 'Stripe', partialName: 'stripe', methodType: 'stripe' }
    ],
    billAddress: null,
    shipAddress: null,
    lineItems: [],
    payments: [],
    shipments: [],
    adjustments: [],
    permissions: { canUpdate: true },
    creditCards: []
  },
  isFetching: false,
  error: null,
  promoCode: { error: null, isFetching: false }
}

export { mockedEmptyCart }
