const mockedFullCart = {
  data: {
    id: 76150,
    number: 'R835071361',
    itemTotal: '60.0',
    total: '60.0',
    shipTotal: '0.0',
    state: 'cart',
    adjustmentTotal: '0.0',
    userId: 2320,
    createdAt: '2020-06-01T22:45:45.234Z',
    updatedAt: '2020-06-03T16:21:02.403Z',
    completedAt: null,
    paymentTotal: '0.0',
    shipmentState: null,
    paymentState: null,
    email: 'francois@chord.co',
    specialInstructions: null,
    channel: 'spree',
    includedTaxTotal: '0.0',
    additionalTaxTotal: '0.0',
    displayIncludedTaxTotal: '$0.00',
    displayAdditionalTaxTotal: '$0.00',
    taxTotal: '0.0',
    currency: 'USD',
    coveredByStoreCredit: false,
    displayTotalApplicableStoreCredit: '$0.00',
    orderTotalAfterStoreCredit: '60.0',
    displayOrderTotalAfterStoreCredit: '$60.00',
    totalApplicableStoreCredit: 0,
    displayTotalAvailableStoreCredit: '$0.00',
    displayStoreCreditRemainingAfterCapture: '$0.00',
    cancelerId: null,
    displayItemTotal: '$60.00',
    totalQuantity: 3,
    displayTotal: '$60.00',
    displayShipTotal: '$0.00',
    displayTaxTotal: '$0.00',
    token: 'CRU_oXXC9icwj4y-vt3zHg',
    checkoutSteps: ['address', 'delivery', 'payment', 'confirm', 'complete'],
    paymentMethods: [
      { id: 23, name: 'Stripe', partialName: 'stripe', methodType: 'stripe' }
    ],
    billAddress: null,
    shipAddress: null,
    lineItems: [
      {
        id: 36648,
        quantity: 2,
        price: '25.0',
        variantId: 409,
        singleDisplayAmount: '$25.00',
        displayAmount: '$50.00',
        total: '50.0',
        variant: {
          id: 409,
          name: 'Cooling Facial Moisturizer',
          sku: 'cooling-facial-moisturizer',
          weight: '5.0',
          height: null,
          width: null,
          depth: null,
          isMaster: true,
          slug: 'cooling-facial-moisturizer',
          description: null,
          trackInventory: false,
          price: '25.0',
          displayPrice: '$25.00',
          optionsText: '',
          inStock: true,
          isBackorderable: false,
          totalOnHand: null,
          isDestroyed: false,
          optionValues: [],
          images: [],
          productId: 113
        },
        adjustments: []
      },
      {
        id: 36649,
        quantity: 1,
        price: '10.0',
        variantId: 412,
        singleDisplayAmount: '$10.00',
        displayAmount: '$10.00',
        total: '10.0',
        variant: {
          id: 412,
          name: 'Cooling Spray',
          sku: 'cooling-spray',
          weight: '5.0',
          height: null,
          width: null,
          depth: null,
          isMaster: true,
          slug: 'cooling-spray',
          description: null,
          trackInventory: false,
          price: '10.0',
          displayPrice: '$10.00',
          optionsText: '',
          inStock: true,
          isBackorderable: false,
          totalOnHand: null,
          isDestroyed: false,
          optionValues: [],
          images: [],
          productId: 116
        },
        adjustments: []
      }
    ],
    payments: [],
    shipments: [],
    adjustments: [],
    permissions: { canUpdate: true },
    creditCards: []
  },
  isFetching: false,
  error: null,
  promoCode: { error: null, isFetching: false }
}
export { mockedFullCart }
